[package]
name = "stack-vector"
version = "0.1.0"
edition = "2024"
description = "Vec-like wrapper for an array allocated in the stack"
authors = ["Sa√∫l Valdelvira <saul@saulv.es>"]
license = "MIT"
readme = "README"
repository = "https://git.saulv.es/stack-vector"

[dependencies]
